### ISSUE TITLE
Active Canny - Edge Detection and Recovery with Open Active Contour Models

### ISSUE THREAD

**Issue by RoyiAvital** [mubastan/canny#1]
Hello,

Could you add [Active Canny: Edge Detection and Recovery with Open Active Contour Models](http://arxiv.org/abs/1609.03415)?

Thank You.

**Comment by tgis-top** [comment]
Actually, I have a big doubt about this atritcle. The Internal Energy give the force that perpendicular to the contour, so only the growing term has effect. And this term is suppressed or enhanced by other unrelated forces，the final result will be confusing.

One possible method might be:
1. Grow the ends of the contour by some pixels with the most gradient.
2. Run the ACM method to adjust the growed contour to the right place.

But still:
1.The growing direction and amount is hard to determine. If only grow by one pixel, after ACM, it might be growed by nothing.
2.It is very easy to grow the contour to the neighbor contour, but they should not be connected actually.

The growing force and growing dircetion of the method in the article is very unclear. if only simply make the growing force proportional to the gradient magnitude, and add it to the ACM equation，the result is nothing growing. If it does growing ，it is the "luck" do its job.

**Comment by cipri-tom** [comment]
This is a good question! @mubastan  do you intend to open source the code for the paper ? No worries if it is still in research phase, the community will be glad to receive it.

**Comment by napsteryogesh** [comment]
Hi, Does this repository have implementation of 
Active Canny - Edge Detection and Recovery with Open Active Contour Models or it is just implementation of classic Canny edge detection.?

**Comment by mubastan** [comment]
This is standard Canny edge detection.

For Active Canny, you may have a look at the paper "Segmentation and tracking of cytoskeletal filaments using open active contours" (code available at http://athena.physics.lehigh.edu/jfilament/).
You can easily extend this to implement Active Canny.
